IMAGE image_SELECTION_BGB "maps/selection/tiles_SELECTION_BGB.png" BEST DUPLICATE
IMAGE image_SELECTION_BGA "maps/selection/tiles_SELECTION_BGA.png" BEST DUPLICATE

IMAGE image_TETE_H_SELECTION "maps/selection/tiles_TETE_H_SELECTION.png" BEST DUPLICATE
IMAGE image_TETE_F_SELECTION "maps/selection/tiles_TETE_F_SELECTION.png" BEST DUPLICATE

TILESET tileset_TETE_H_SELECTION "maps/selection/tiles_TETE_H_SELECTION.png" NONE DUPLICATE
TILESET tileset_TETE_F_SELECTION "maps/selection/tiles_TETE_F_SELECTION.png" NONE DUPLICATE