IMAGE image_NIVEAU1_WINDOW "maps/global/tiles_NIVEAU1_WINDOW.png" NONE DUPLICATE
IMAGE image_NIVEAU1_BGB "maps/niveau1/tiles_NIVEAU1_BGB.png" NONE DUPLICATE //16400 // (16384)+16
IMAGE image_NIVEAU1_BGA "maps/niveau1/tiles_NIVEAU1_BGA.png" NONE DUPLICATE //57535 // 24576+32768+191

TILESET tileset_NIVEAU1_BGB "maps/niveau1/tiles_NIVEAU1_BGB.png" NONE DUPLICATE
TILESET tileset_NIVEAU1_BGA "maps/niveau1/tiles_NIVEAU1_BGA.png" NONE DUPLICATE
TILESET tileset_NIVEAU1_WINDOW "maps/global/tiles_NIVEAU1_WINDOW.png" NONE DUPLICATE

TILESET tileset_COLLISION_NIVEAU1 "maps/niveau1/tilemap_COLLISION_NIVEAU1.png" NONE DUPLICATE
TILESET tileset_ENNEMIS_NIVEAU1 "maps/niveau1/tilemap_ENNEMIS_NIVEAU1.png" NONE DUPLICATE

MAP tilemap_COLLISION_NIVEAU1 "maps/niveau1/tilemap_COLLISION_NIVEAU1.png" tileset_COLLISION_NIVEAU1 BEST 0
MAP tilemap_ENNEMIS_NIVEAU1 "maps/niveau1/tilemap_ENNEMIS_NIVEAU1.png" tileset_ENNEMIS_NIVEAU1 BEST 0