IMAGE image_NIVEAU1_BGB "maps/niveau1/tiles_NIVEAU1_BGB.png" NONE DUPLICATE
IMAGE image_NIVEAU1_BGA "maps/niveau1/tiles_NIVEAU1_BGA.png" NONE DUPLICATE


TILESET tileset_NIVEAU1_BGB "maps/niveau1/tiles_NIVEAU1_BGB.png" NONE DUPLICATE
TILESET tileset_NIVEAU1_BGA "maps/niveau1/tiles_NIVEAU1_BGA.png" NONE DUPLICATE


TILESET tileset_COLLISION_NIVEAU1 "maps/niveau1/tilemap_COLLISION_NIVEAU1.png" NONE DUPLICATE

MAP tilemap_COLLISION_NIVEAU1 "maps/niveau1/tilemap_COLLISION_NIVEAU1.png" tileset_COLLISION_NIVEAU1 BEST 0