#ifndef _RES_SPRITES_JEU_H_
#define _RES_SPRITES_JEU_H_

extern const SpriteDefinition tiles_Sprite_TITRE;
extern const SpriteDefinition tiles_Sprite_MENU_TITRE;
extern const SpriteDefinition tiles_Sprite_BOUTON_OPTIONS;
extern const SpriteDefinition tiles_Sprite_PLAYER_OPTIONS;
extern const SpriteDefinition tiles_Sprite_CREDITS_OPTIONS;
extern const SpriteDefinition tiles_Sprite_START_OPTIONS;
extern const SpriteDefinition tiles_Sprite_CHIFFRES_OPTIONS;
extern const SpriteDefinition tiles_Sprite_PRESS_START;
extern const SpriteDefinition tiles_Sprite_VIE_H;
extern const SpriteDefinition tiles_Sprite_VIE_F;
extern const SpriteDefinition tiles_Sprite_CREDITS;
extern const SpriteDefinition tiles_Sprite_CHIFFRES;
extern const SpriteDefinition tiles_Sprite_GAMEOVER;
extern const SpriteDefinition tiles_Sprite_PAUSE;
extern const SpriteDefinition tiles_Sprite_ROUND;
extern const SpriteDefinition tiles_Sprite_1;
extern const SpriteDefinition tiles_Sprite_JOUEUR_H_BAS;
extern const SpriteDefinition tiles_Sprite_JOUEUR_H_HAUT;
extern const SpriteDefinition tiles_Sprite_JOUEUR_F_BAS;
extern const SpriteDefinition tiles_Sprite_JOUEUR_F_HAUT;
extern const SpriteDefinition tiles_Sprite_AURA_H;
extern const SpriteDefinition tiles_Sprite_AURA_F;
extern const SpriteDefinition tiles_Sprite_BALLE;
extern const SpriteDefinition tiles_Sprite_SHURIKEN;
extern const SpriteDefinition tiles_Sprite_DRAGON;
extern const SpriteDefinition tiles_Sprite_SPLASH;
extern const SpriteDefinition tiles_Sprite_KIWI;
extern const SpriteDefinition tiles_Sprite_CAROTTE;
extern const SpriteDefinition tiles_repere_BG;
extern const SpriteDefinition tiles_repere_BD;
extern const SpriteDefinition tiles_repere_HG;
extern const SpriteDefinition tiles_repere_HD;
extern const SpriteDefinition tiles_Sprite_ESCARGOT_H;
extern const SpriteDefinition tiles_Sprite_BULOT;
extern const SpriteDefinition tiles_Sprite_ESCARGOT_V;
extern const SpriteDefinition tiles_Sprite_MORSE;
extern const SpriteDefinition tiles_Sprite_POULPE;
extern const SpriteDefinition tiles_Sprite_PELICAN;
extern const SpriteDefinition tiles_Sprite_PLATEFORME;

#endif // _RES_SPRITES_JEU_H_
